import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import mainCss from "./main.module.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RouteItem {
  text: string;
  route: string;
}

function HomeIcon() {
  return (
    <svg className="fill-plum-900 size-14" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><path d="M392.8 1.2c-17-4.9-34.7 5-39.6 22l-128 448c-4.9 17 5 34.7 22 39.6s34.7-5 39.6-22l128-448c4.9-17-5-34.7-22-39.6zm80.6 120.1c-12.5 12.5-12.5 32.8 0 45.3L562.7 256l-89.4 89.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l112-112c12.5-12.5 12.5-32.8 0-45.3l-112-112c-12.5-12.5-32.8-12.5-45.3 0zm-306.7 0c-12.5-12.5-32.8-12.5-45.3 0l-112 112c-12.5 12.5-12.5 32.8 0 45.3l112 112c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L77.3 256l89.4-89.4c12.5-12.5 12.5-32.8 0-45.3z"/></svg>
  );
}

function MenuIcon() {
  return (
    <svg className="fill-plum-800 size-10" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"  viewBox="0 0 50 50">
<path d="M 5 8 A 2.0002 2.0002 0 1 0 5 12 L 45 12 A 2.0002 2.0002 0 1 0 45 8 L 5 8 z M 5 23 A 2.0002 2.0002 0 1 0 5 27 L 45 27 A 2.0002 2.0002 0 1 0 45 23 L 5 23 z M 5 38 A 2.0002 2.0002 0 1 0 5 42 L 45 42 A 2.0002 2.0002 0 1 0 45 38 L 5 38 z"></path>
</svg>
);
}

export default function RootLayout({
  children,
  options = [
    {
      text: "Home",
      route: "/"
    },
    {
      text: "Test",
      route: "/test"
    }  
  ]
}: Readonly<{
  children: React.ReactNode;
  options: RouteItem[];
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <div className={mainCss.grid} >
          <header className={mainCss.header} ></header>
          <aside className={mainCss.aside} >
            <button className={mainCss.menuButton}><MenuIcon /></button>
            <nav className="">  
              <ul className={mainCss.menu}>
                {options.map(({ text, route }, index) => (
                  <li key={index} className="my-4">
                    <a href={route}>{text}</a>
                  </li>
                ))}
              </ul>
            </nav>
          </aside>
          <main className={mainCss.main} >
            {children}
          </main>
        </div>
        
      </body>
    </html>
  );
  
}
